In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


DEPRECATION: Loading egg at c:\program files\python311\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Hermitian Matrices, Unitary Matrices and Tensor Product


# Understanding Complex Hermitian and Unitary Matrices

This tutorial delves into two pivotal concepts in quantum computing and linear algebra: complex Hermitian and Unitary matrices. Both play critical roles in quantum mechanics and quantum computing, underpinning the behavior of quantum systems and the operations performed on them.

## Objectives
- Define and explore the properties of complex Hermitian matrices.
- Understand and implement complex Unitary matrices in Python.
- Highlight their significance and applications in quantum computing.

Prepare to enhance your mathematical toolkit with these foundational concepts, illustrated with Python examples for a hands-on learning experience.



## Complex Hermitian Matrices

A Hermitian matrix, or self-adjoint matrix, is a square matrix that is equal to its own conjugate transpose. This property makes it a natural representation of observable quantities in quantum mechanics.

### Properties
- The eigenvalues of a Hermitian matrix are always real.
- The eigenvectors of a Hermitian matrix corresponding to different eigenvalues are orthogonal.
- Hermitian matrices are extensively used in quantum mechanics to describe physical observables.

### Python Example: Defining a Hermitian Matrix


In [ ]:

import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[2+0j, 2-1j], [2+1j, 3+0j]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)

is_hermitian, hermitian_matrix



## Complex Unitary Matrices

A Unitary matrix is a square matrix whose conjugate transpose is also its inverse. Unitary matrices preserve the inner product, making them essential for describing quantum gates and evolution in quantum computing.

### Properties
- Preserves the norm of vectors, hence preserving quantum states during transformations.
- The determinant of a Unitary matrix has an absolute value of 1.
- Used to represent reversible quantum operations and time evolution in quantum systems.

### Python Example: Defining a Unitary Matrix


In [ ]:

# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

is_unitary, unitary_matrix


# Tensor product


## Tensor Product for Complex Vectors

The tensor product of two complex vectors creates a new vector in a higher-dimensional space, allowing us to combine quantum states in quantum computing.

### Example


In [ ]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+2j, 3+4j])
v2 = np.array([5+6j, 7+8j])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v



## Tensor Product for Complex Matrices

The tensor product for matrices combines individual matrices into a larger matrix, crucial for representing multiple qubit systems in quantum computing.

### Example


In [ ]:

# Define two complex matrices for the tensor product
M1 = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
M2 = np.array([[9+10j, 11+12j], [13+14j, 15+16j]])

# Calculate the tensor product
tensor_product_m = np.kron(M1, M2)

tensor_product_m


# Exercises on Complex Vector and Matrix Operations

This set of exercises is designed to test your understanding of various concepts related to complex vector and matrix operations, which are foundational in quantum computing. Each exercise presents a concrete case for you to apply what you've learned about Hermitian matrices, Unitary matrices, and tensor products.

NOTE: VERIFY YOUR COMPUTATIONS IN PAPER AND IN THE COMPUTER.



## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.


In [2]:
import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[3, 2-1j], [2+1j, 1]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)

is_hermitian, hermitian_matrix

(True,
 array([[3.+0.j, 2.-1.j],
        [2.+1.j, 1.+0.j]]))

## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.


In [3]:
# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)*1j], [1/np.sqrt(2)*1j, 1/np.sqrt(2)]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

is_unitary, unitary_matrix

(True,
 array([[0.70710678+0.j        , 0.        +0.70710678j],
        [0.        +0.70710678j, 0.70710678+0.j        ]]))

## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.

In [4]:
import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+1j, 2-1j])
v2 = np.array([1-2j, 3])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v

array([3.-1.j, 3.+3.j, 0.-5.j, 6.-3.j])

## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.

In [5]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([[0, 1], [1, 0]])
v2 = np.array([[1j, 0], [0, -1j]])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v

array([[0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.-0.j, 0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.-1.j, 0.+0.j, 0.-0.j]])

## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

In [8]:
import numpy as np

def beam_splitter():
    """Matriz del divisor de haz (BS)."""
    factor = 1 / np.sqrt(2)
    BS = np.array([[1, 1j], [1j, 1]])
    return factor * BS

def mirror():
    """Matriz del espejo (M)."""
    return np.array([[0, 1], [1, 0]])

def phase_shifter(theta):
    """Matriz del cambiador de fase (P)."""
    P = np.array([[1, 0], [0, np.exp(1j * theta)]])
    return P

def mach_zehnder(theta):
    """Simulación del interferómetro de Mach-Zehnder paso a paso."""
    # Estado inicial: el fotón comienza en el camino 0
    psi_in = np.array([1, 0])
    print("Estado inicial:", psi_in)
    
    # Primer divisor de haz (BS)
    BS1 = beam_splitter()
    psi1 = np.dot(BS1, psi_in)
    print("Después del primer BS:", psi1)
    
    # Cambiador de fase (P)
    P = phase_shifter(theta)
    psi2 = np.dot(P, psi1)
    print("Después del cambiador de fase:", psi2)
    
    # Espejo (M)
    M = mirror()
    psi3 = np.dot(M, psi2)
    print("Después del espejo:", psi3)
    
    # Segundo divisor de haz (BS)
    BS2 = beam_splitter()
    psi_out = np.dot(BS2, psi3)
    print("Después del segundo BS:", psi_out)
    
    return psi_out

# Definir el ángulo de fase
theta = np.pi / 2  # 90 grados de fase
resultado = mach_zehnder(theta)

# Mostrar el resultado final
print("Estado de salida final:", resultado)

Estado inicial: [1 0]
Después del primer BS: [0.70710678+0.j         0.        +0.70710678j]
Después del cambiador de fase: [ 0.70710678+0.00000000e+00j -0.70710678+4.32978028e-17j]
Después del espejo: [-0.70710678+4.32978028e-17j  0.70710678+0.00000000e+00j]
Después del segundo BS: [-0.5+0.5j  0.5-0.5j]
Estado de salida final: [-0.5+0.5j  0.5-0.5j]


## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)


In [11]:
import numpy as np

def hadamard(n):
    """Genera la matriz de Hadamard de tamaño 2^n x 2^n."""
    H = (1 / np.sqrt(2)) * np.array([[1, 1], [1, -1]])
    if n == 2:
        return np.kron(H, H)  # Producto de Kronecker para 2 qubits
    return H

def uf_matrix():
    """Matriz Uf proporcionada en la imagen."""
    return np.array([
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]
    ])

def deutsch_algorithm():
    """Implementación paso a paso del algoritmo de Deutsch."""
    # 1. Estado inicial |0⟩ ⊗ |1⟩
    psi = np.array([1, 0, 0, 0])  # Representación del estado |00⟩
    print("Estado inicial:", psi)
    
    # 2. Aplicar Hadamard en ambos qubits
    H2 = hadamard(2)
    psi = H2 @ psi
    print("Después de Hadamard en ambos qubits:", psi)
    
    # 3. Aplicar la función Uf
    Uf = uf_matrix()
    psi = Uf @ psi
    print("Después de aplicar Uf:", psi)
    
    # 4. Aplicar Hadamard en el primer qubit
    H1 = np.kron(hadamard(1), np.eye(2))  # Hadamard solo en el primer qubit
    psi = H1 @ psi
    print("Después de Hadamard en el primer qubit:", psi)
    
    # 5. Medir el primer qubit (nos interesa la probabilidad de |0⟩ o |1⟩)
    prob_0 = np.abs(psi[0])**2 + np.abs(psi[1])**2
    prob_1 = np.abs(psi[2])**2 + np.abs(psi[3])**2
    
    # 6. Decidir el resultado de la medición
    resultado = 0 if prob_0 > prob_1 else 1
    print("Probabilidad de medir |0⟩:", prob_0)
    print("Probabilidad de medir |1⟩:", prob_1)
    print("Resultado final del algoritmo de Deutsch:", resultado)

# Ejecutar el algoritmo
deutsch_algorithm()



Estado inicial: [1 0 0 0]
Después de Hadamard en ambos qubits: [0.5 0.5 0.5 0.5]
Después de aplicar Uf: [0.5 0.5 0.5 0.5]
Después de Hadamard en el primer qubit: [0.70710678 0.70710678 0.         0.        ]
Probabilidad de medir |0⟩: 0.9999999999999996
Probabilidad de medir |1⟩: 0.0
Resultado final del algoritmo de Deutsch: 0
